### PR TITLE
Add POST command

### PR DESCRIPTION
**Pull request by thebandit**
Allow posting of a message via the POST command. 

I tried to keep it in line with the Pear lib's mail() method per some of your comments here although instinct is telling me to make the headers an array. If you agree I can amend the pull request.

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
Hi @thebandit, thanks for your PR! It looks good to me, but it still needs some unit tests. Can you please add them?

**Comment by thebandit** [comment]
Hi, I'll see what I can do. Never done a unit test before so I need some time to figure out what's what.

**Comment by robinvdvleuten** [comment]
@thebandit no worries take your time! If you need some guidance let me know :)

**Comment by thebandit** [comment]
Hi, I've added some unit tests, hopefully they are sufficient.

**Comment by robinvdvleuten** [comment]
Awesome thanks @thebandit!

**Pull request merged**
