### PR TITLE
add LIST command based on RFC3977

### PR DESCRIPTION
**Pull request by ctrl-f5**
function name cannot be "list" in < php7 so "listGroups" seemed like the best alternative

### CODE REVIEW

**Comment by ctrl-f5** [comment]
I'm looking into writing a test for the command aswel

**Comment by robinvdvleuten** [comment]
Awesome! Thanks @ctrl-f5

**Comment by Anahkiasen** [comment]
This is a bit counterintuitive because NNTP already has a `LISTGROUP` command which does something different

**Comment by robinvdvleuten** [comment]
@Anahkiasen good point, do you have any suggestions for the method name? ->list() isn't possible as the lib supports php 5.5

**Comment by Anahkiasen** [comment]
Hm `getGroups` could work I guess or `listAvailableGroups` or something like that, not sure

**Pull request merged**
